### ISSUE TITLE
VCR_BUFFER_TIME_MILLIS isn't really used, or is it?

### ISSUE THREAD

**Issue by casidiablo** [scopely/kinesis-vcr#18]
Documentation mentions `VCR_BUFFER_TIME_MILLIS` as a way to

> _control how long to buffer data before writing to S3_

But the code says otherwise.

**Comment by avram** [comment]
```
        bufferTimeMillis = Long.parseLong(getenv.getOrDefault("VCR_BUFFER_TIME_MILLIS", String.valueOf(bufferTimeMillis)));
```

https://github.com/scopely/kinesis-vcr/blob/52d1f27e8603c538a2c8df5847368d06ba79e0cb/src/main/java/com/scopely/infrastructure/kinesis/VcrConfiguration.java#L22

```
        properties.setProperty(KinesisConnectorConfiguration.PROP_BUFFER_MILLISECONDS_LIMIT,
                String.valueOf(vcrConfiguration.bufferTimeMillis));
```

https://github.com/scopely/kinesis-vcr/blob/7f5a0d2fd1dfc6caa6d391fe8bb10e7bd7c017af/src/main/java/com/scopely/infrastructure/kinesis/KinesisRecorder.java#L33

Setting the property is enough for the connector pipeline to use it. Are you seeing an issue here? The core of the recorder is just the Kinesis Connector library.

**Comment by casidiablo** [comment]
Oh, I see it now. No problems here then.
